services:
  app:
    build: .
    container_name: comments_app
    environment:
      DB_NAME: comments
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_SSL_MODE: disable
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - comments_network
  db:
    image: postgres:17.4-alpine
    container_name: comments_db
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - comments_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d comments"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - comments_db_data:/var/lib/postgresql/data
networks:
  comments_network:
    driver: bridge
volumes:
  comments_db_data: {}
