# https://taskfile.dev

version: "3"

tasks:
  build:
    desc: "Build the app"
    cmds:
      - go build -o server cmd/server/main.go
    sources:
      - ./*.go
    generates:
      - server{{exeExt}}
  test:
    desc: "Run all tests"
    cmds:
      - go test -tags=unit,integration,e2e ./...
  test-unit:
    desc: "Run unit tests"
    cmds:
      - go test -v -tags=unit ./...
  test-it:
    desc: "Run integration tests"
    cmds:
      - go test -v -tags=integration ./...
  test-e2e:
    desc: "Run e2e tests"
    cmds:
      - go test -v -tags=e2e ./...
  lint:
    desc: "Run linters"
    cmds:
      - golangci-lint run ./...
  run:
    desc: "Run the app in docker compose"
    cmds:
      - docker compose up --build
